from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import index, get_posts, get_post, create_post, update_post, patch_post, delete_post, post_methods, PostViewSet

router = DefaultRouter()
router.register(r'posts', PostViewSet)

urlpatterns = [
    path('', index),  # Endpoint for the root URL
    path('api/', include(router.urls)),  # Include the URLs generated by the router
    path('api/post/', post_methods),  # Endpoint for handling all methods for /api/post/
    path('api/posts/', get_posts),  # Endpoint for getting all posts
    path('api/posts/<int:post_id>/', get_post),  # Endpoint for getting a specific post
    path('api/posts/create/', create_post),  # Endpoint for creating a post
    path('api/posts/update/<int:post_id>/', update_post),  # Endpoint for updating a post
    path('api/posts/patch/<int:post_id>/', patch_post),  # Endpoint for partially updating a post
    path('api/posts/delete/<int:post_id>/', delete_post),  # Endpoint for deleting a post
]
